version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: project-brain-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: project-brain-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: project-brain-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build: .
    container_name: project-brain-api
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - /home/sa/projects/staffprobot:/projects/staffprobot:ro
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_HOST=http://chromadb:8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - ollama
      - chromadb
      - redis
    restart: unless-stopped

volumes:
  ollama_data:
  chroma_data:
  redis_data:
