version: '3.8'

services:
  api-client:
    build: .
    container_name: project-brain-prod-client
    ports:
      - "8002:8001"
    environment:
      - LOCAL_API_URL=http://<LOCAL_IP>:8001
      - REDIS_URL=redis://redis:6379
      - MODE=client
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: project-brain-prod-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
