projects:
  - name: staffprobot
    path: /projects/staffprobot
    git_url: https://github.com/your-org/staffprobot
    index_patterns:
      - "**/*.py"
      - "**/*.md"
      - "**/*.html"
    exclude_patterns:
      - "**/venv/**"
      - "**/__pycache__/**"
      - "**/node_modules/**"
      - "**/.git/**"
    rules_path: "doc/conventions.mdc"
    description: "StaffProBot - система управления персоналом"
